// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2S_LGebIbEhP2gaXzXmrZ88Mo9mYyj5U',
    appId: '1:711383704726:web:553a72b89ec4c915084eb7',
    messagingSenderId: '711383704726',
    projectId: 'hikingapp-bd43d',
    authDomain: 'hikingapp-bd43d.firebaseapp.com',
    storageBucket: 'hikingapp-bd43d.firebasestorage.app',
    measurementId: 'G-WC9XTNK3CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnsn4Yh6fo2K2a28fdaaBLm4TMVbv5qk',
    appId: '1:711383704726:android:474bd0cb7f700141084eb7',
    messagingSenderId: '711383704726',
    projectId: 'hikingapp-bd43d',
    storageBucket: 'hikingapp-bd43d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHEuqMGV53tAJwxcnjlesQQcTC6aVcWk',
    appId: '1:711383704726:ios:f445a511c619f75a084eb7',
    messagingSenderId: '711383704726',
    projectId: 'hikingapp-bd43d',
    storageBucket: 'hikingapp-bd43d.firebasestorage.app',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHEuqMGV53tAJwxcnjlesQQcTC6aVcWk',
    appId: '1:711383704726:ios:f445a511c619f75a084eb7',
    messagingSenderId: '711383704726',
    projectId: 'hikingapp-bd43d',
    storageBucket: 'hikingapp-bd43d.firebasestorage.app',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2S_LGebIbEhP2gaXzXmrZ88Mo9mYyj5U',
    appId: '1:711383704726:web:3c5c8bd623e5da1b084eb7',
    messagingSenderId: '711383704726',
    projectId: 'hikingapp-bd43d',
    authDomain: 'hikingapp-bd43d.firebaseapp.com',
    storageBucket: 'hikingapp-bd43d.firebasestorage.app',
    measurementId: 'G-DCGTJ8TBCH',
  );
}
